// ═══════════════════════════════════════════════════════════════════
// بيانات الشركات — مُوحَّدة ومُتحقَّق منها عبر الإنترنت
// آخر تحديث: مارس 2026
// ═══════════════════════════════════════════════════════════════════
// • كل شركة تظهر مرة واحدة فقط (بدون تكرار فروع وهمية)
// • regions[] = المناطق الحقيقية التي يوجد بها مقر أو فرع فعلي
// • الشركات الدولية الكبرى: مقرها السعودي في الرياض ما لم يثبت غير ذلك
// • تم حذف الجهات غير التقنية (مستشفيات، إدارات صحية، صناديق زراعية...)
// ═══════════════════════════════════════════════════════════════════

export const companies = [

  // ────────────────────────────────────────────────────────────────
  //  الرياض — شركات دولية كبرى (مكاتب إقليمية في الرياض)
  // ────────────────────────────────────────────────────────────────
  { name: "مايكروسوفت السعودية (Microsoft)", region: "الرياض", regions: ["الرياض"], size: "كبيرة", spec: "سحابة (Azure)، ذكاء اصطناعي، برمجيات مؤسسية", web: "https://careers.microsoft.com/students", contact: "microsoft.com/en-sa/contact", linkedin: "https://linkedin.com/company/microsoft", training: "Global University Internship — مفتوح لجميع الجنسيات", grade: "A+", nonSaudi: "نعم — برنامج عالمي مفتوح لجميع الجنسيات" },
  { name: "جوجل السعودية (Google)", region: "الرياض", regions: ["الرياض"], size: "كبيرة", spec: "سحابة (GCP)، ذكاء اصطناعي، بحث، إعلانات", web: "https://careers.google.com/students/", contact: "google.com/contact", linkedin: "https://linkedin.com/company/google", training: "STEP Internship + Student Researcher — للمتميزين", grade: "A+", nonSaudi: "نعم — برنامج STEP متاح للطلاب الدوليين" },
  { name: "أمازون ويب سيرفسز (AWS)", region: "الرياض", regions: ["الرياض"], size: "كبيرة", spec: "حوسبة سحابية، DevOps، مراكز بيانات", web: "https://amazon.jobs", contact: "aws.amazon.com/contact-us", linkedin: "https://linkedin.com/company/amazon-web-services", training: "Data Center Intern — مسارات تنتهي بالتوظيف", grade: "A+", nonSaudi: "نعم — تقبل طلاب دوليين متفوقين" },
  { name: "أوراكل السعودية (Oracle)", region: "الرياض", regions: ["الرياض"], size: "كبيرة", spec: "قواعد بيانات، سحابة، ERP", web: "https://www.oracle.com/sa/", contact: "oracle.com/sa/corporate/contact", linkedin: "https://linkedin.com/company/oracle", training: "مبادرة «مستقبلي» — تدريب وشهادات مجانية لجميع المقيمين", grade: "A+", nonSaudi: "نعم — متاحة لجميع المقيمين" },
  { name: "SAP السعودية", region: "الرياض", regions: ["الرياض"], size: "كبيرة", spec: "ERP، سحابة، S/4HANA", web: "https://jobs.sap.com/content/students/", contact: "+966 11 218 6666", linkedin: "https://linkedin.com/company/sap", training: "برنامج iXp — مفتوح (160 جنسية في فرقهم)", grade: "A+", nonSaudi: "نعم — ترحب بجميع الجنسيات" },
  { name: "سيسكو السعودية (Cisco)", region: "الرياض", regions: ["الرياض"], size: "كبيرة", spec: "شبكات، أمن سيبراني، سحابة", web: "https://careers.cisco.com/global/en/internships-and-co-ops", contact: "cisco.com/support", linkedin: "https://linkedin.com/company/cisco", training: "COOP & Summer Internship + أكاديمية سيسكو", grade: "A+", nonSaudi: "نعم — بيئة عمل عالمية شاملة" },
  { name: "IBM السعودية", region: "الرياض", regions: ["الرياض"], size: "كبيرة", spec: "ذكاء اصطناعي (Watson)، سحابة، استشارات", web: "https://www.ibm.com/careers/internships", contact: "ibm.com/sa-en/contact", linkedin: "https://linkedin.com/company/ibm", training: "تدريب صيفي وتعاوني — تخصصات AI/Cloud", grade: "A+", nonSaudi: "نعم — معايير عالمية في القبول" },
  { name: "هواوي السعودية (Huawei)", region: "الرياض (شراكات في حائل)", regions: ["الرياض", "حائل"], size: "كبيرة", spec: "معدات اتصالات، 5G، سحابة", web: "https://www.huawei.com", contact: "8001220888", linkedin: "https://linkedin.com/company/huawei", training: "Seeds for the Future + تدريب تعاوني + شراكة مع جامعة حائل", grade: "A+", nonSaudi: "نعم — بيئة دولية" },
  { name: "ديل تكنولوجيز (Dell)", region: "الرياض", regions: ["الرياض"], size: "كبيرة", spec: "أجهزة، سحابة، حلول تقنية", web: "https://www.dell.com/en-sa", contact: "dell.com/support", linkedin: "https://linkedin.com/company/delltechnologies", training: "Dell تدريب — dell.com/careers", grade: "A", nonSaudi: "نعم — توظيف دولي" },
  { name: "إريكسون السعودية (Ericsson)", region: "الرياض", regions: ["الرياض"], size: "كبيرة", spec: "5G، بنية تحتية للاتصالات", web: "https://www.ericsson.com", contact: "ericsson.com/en/contact", linkedin: "https://linkedin.com/company/ericsson", training: "تدريب وبرامج خريجين", grade: "A", nonSaudi: "نعم — توظيف دولي" },
  { name: "أكسنتشر السعودية (Accenture)", region: "الرياض", regions: ["الرياض"], size: "كبيرة", spec: "استشارات، تحول رقمي", web: "https://www.accenture.com/sa-en", contact: "accenture.com/sa-en/contact-us", linkedin: "https://linkedin.com/company/accenture", training: "Technology COOP Trainee — مشاريع تحول رقمي", grade: "A", nonSaudi: "نعم — بيئة شاملة تقبل غير السعوديين" },
  { name: "هانيويل السعودية (Honeywell)", region: "الرياض", regions: ["الرياض"], size: "كبيرة", spec: "أنظمة تحكم، تقنية صناعية، IoT", web: "https://www.honeywell.com", contact: "honeywell.com/careers", linkedin: "https://linkedin.com/company/honeywell", training: "برنامج Early Careers — تدريب دولي", grade: "A", nonSaudi: "نعم — برامج دولية" },
  { name: "بوش (Bosch Group)", region: "الرياض", regions: ["الرياض"], size: "كبيرة", spec: "هندسة، IT، أتمتة", web: "https://www.bosch.com.sa", contact: "bosch.com/careers", linkedin: "https://linkedin.com/company/bosch", training: "Trainee Internship — متاح لخريجي الجامعات السعودية (كافة الجنسيات)", grade: "A", nonSaudi: "نعم — كافة الجنسيات" },
  { name: "F5 Networks", region: "الرياض", regions: ["الرياض"], size: "كبيرة", spec: "أمن سيبراني، سحابة، شبكات", web: "https://www.f5.com", contact: "f5.com/company/careers", linkedin: "https://linkedin.com/company/f5-networks", training: "تدريب Channel Sales متاح للمقيمين", grade: "", nonSaudi: "نعم — توظيف دولي" },
  { name: "HP / HPE السعودية", region: "الرياض", regions: ["الرياض"], size: "كبيرة", spec: "أجهزة، حلول تقنية مؤسسية", web: "https://www.hp.com/sa-en/", contact: "hp.com/support", linkedin: "https://linkedin.com/company/hewlett-packard-enterprise", training: "تدريب فني وإداري", grade: "", nonSaudi: "نعم — متاح للمقيمين المؤهلين" },

  // ────────────────────────────────────────────────────────────────
  //  الرياض — شركات استشارات (Big Four + أخرى)
  // ────────────────────────────────────────────────────────────────
  { name: "ديلويت السعودية (Deloitte)", region: "الرياض", regions: ["الرياض"], size: "كبيرة", spec: "استشارات، أمن سيبراني، تحول رقمي", web: "https://www.deloitte.com/middle-east/en/careers/explore-your-fit/students/internship-program.html", contact: "عبر بوابة التوظيف", linkedin: "https://linkedin.com/company/deloitte", training: "برنامج «تدرّب» (Tadarab) — معايير قبول عالمية", grade: "A", nonSaudi: "نعم — تقبل المقيمين بمعايير عالمية" },
  { name: "PwC الشرق الأوسط", region: "الرياض", regions: ["الرياض"], size: "كبيرة", spec: "خدمات تقنية، استشارات", web: "https://careers.pwc.com", contact: "عبر بوابة التوظيف", linkedin: "https://linkedin.com/company/pwc", training: "COOP & Summer Internship", grade: "A", nonSaudi: "محتمل — متاح للمؤهلين (لغة إنجليزية قوية)" },
  { name: "KPMG السعودية", region: "الرياض", regions: ["الرياض"], size: "كبيرة", spec: "استشارات، تقنية", web: "https://kpmg.com/careers", contact: "عبر بوابة التوظيف", linkedin: "https://linkedin.com/company/kpmg", training: "تدريب تعاوني — متاح لجميع الجنسيات", grade: "A", nonSaudi: "نعم — متاح للطلاب من جميع الجنسيات" },
  { name: "EY السعودية (Ernst & Young)", region: "الرياض", regions: ["الرياض"], size: "كبيرة", spec: "تحول رقمي، بيانات، استشارات", web: "https://www.ey.com/en_sa/careers/students-apply-here", contact: "عبر بوابة التوظيف", linkedin: "https://linkedin.com/company/ernstandyoung", training: "تدريب تعاوني — التخصصات التقنية", grade: "A", nonSaudi: "نعم — متاح للمقيمين" },
  { name: "ديفوتيم السعودية (Devoteam)", region: "الرياض", regions: ["الرياض"], size: "كبيرة", spec: "تحول رقمي، سحابة (Google/AWS Partner)", web: "https://careers.devoteam.com/", contact: "عبر بوابة التوظيف", linkedin: "https://linkedin.com/company/devoteam", training: "تدريب للمتميزين تقنياً", grade: "", nonSaudi: "نعم — تقبل كفاءات دولية" },
  { name: "TCS السعودية (Tata Consultancy Services)", region: "الرياض", regions: ["الرياض"], size: "كبيرة", spec: "استشارات تقنية، تعهيد برمجيات، تحول رقمي", web: "https://www.tcs.com/careers", contact: "عبر بوابة التوظيف", linkedin: "https://linkedin.com/company/tata-consultancy-services", training: "تدريب عالمي ومسارات خريجين", grade: "A+", nonSaudi: "نعم — شركة عالمية تقبل كفاءات دولية" },
  { name: "Wipro السعودية", region: "الرياض", regions: ["الرياض"], size: "كبيرة", spec: "استشارات تقنية، خدمات سحابية، أمن سيبراني", web: "https://careers.wipro.com/", contact: "helpdesk.recruitment@wipro.com", linkedin: "https://linkedin.com/company/wipro", training: "Early Careers + Internship", grade: "A+", nonSaudi: "نعم — شركة عالمية تقبل كفاءات دولية" },
  { name: "Atos السعودية", region: "الرياض", regions: ["الرياض"], size: "كبيرة", spec: "تحول رقمي، سحابة هجينة، أمن سيبراني، بيانات وذكاء اصطناعي", web: "https://atos.net/en/join-us", contact: "https://atos.net/en/contact-us", linkedin: "https://linkedin.com/company/atos", training: "Interns and Apprentices + Young Professionals", grade: "A+", nonSaudi: "نعم — برامج دولية للطلاب والخريجين" },
  { name: "هورفاث (Horvath)", region: "الرياض", regions: ["الرياض"], size: "متوسطة", spec: "استشارات هندسية وتقنية", web: "https://www.horvath-partners.com", contact: "عبر بوابة التوظيف", linkedin: "https://linkedin.com/company/horvath-partners", training: "تدريب — يشترط إقامة سارية فقط", grade: "", nonSaudi: "نعم — يشترط فقط إقامة سارية" },
  { name: "روتشيلد آند كو (Rothschild)", region: "الرياض", regions: ["الرياض"], size: "كبيرة", spec: "استشارات مالية وتقنية", web: "https://www.rothschildandco.com/en/careers/students-and-graduates/", contact: "عبر بوابة التوظيف", linkedin: "https://linkedin.com/company/rothschild-and-co", training: "تدريب لطلاب السنة الأخيرة المتميزين", grade: "", nonSaudi: "نعم — متاح" },

  // ────────────────────────────────────────────────────────────────
  //  الرياض — شركات سعودية كبرى
  // ────────────────────────────────────────────────────────────────
  { name: "STC — شركة الاتصالات السعودية", region: "الرياض (فروع في كل المناطق)", regions: ["الرياض", "حائل", "القصيم"], size: "كبيرة", spec: "اتصالات، خدمات رقمية، تقنية معلومات", web: "https://www.stc.com.sa", contact: "900", linkedin: "https://linkedin.com/company/stc", training: "تعاوني وصيفي — stc.com.sa/careers", grade: "A+", nonSaudi: "محدود — معظمه سعوديين عبر تمهير/COOP" },
  { name: "موبايلي — اتحاد اتصالات (Mobily)", region: "الرياض (فروع في كل المناطق)", regions: ["الرياض", "حائل", "القصيم"], size: "كبيرة", spec: "اتصالات، تقنية معلومات، 5G", web: "https://www.mobily.com.sa", contact: "1100", linkedin: "https://linkedin.com/company/mobily", training: "تعاوني وتدريب عبر بوابة التوظيف", grade: "A", nonSaudi: "محتمل — الأغلب سعوديين" },
  { name: "زين السعودية (Zain KSA)", region: "الرياض (فروع في كل المناطق)", regions: ["الرياض", "حائل", "القصيم"], size: "كبيرة", spec: "اتصالات، 5G، حلول رقمية", web: "https://www.sa.zain.com", contact: "959", linkedin: "https://linkedin.com/company/zain-ksa", training: "تعاوني وصيفي", grade: "A", nonSaudi: "محتمل — الأغلب سعوديين" },
  { name: "شركة علم (Elm)", region: "الرياض", regions: ["الرياض"], size: "كبيرة", spec: "حلول حكومة رقمية، ذكاء اصطناعي، خدمات إلكترونية", web: "https://www.elm.sa", contact: "careers@elm.sa | +966112887444", linkedin: "https://linkedin.com/company/elm-company", training: "تعاوني وتمهير — elm.sa/en/career", grade: "A+", nonSaudi: "محدود — فرص محدودة لغير السعوديين" },
  { name: "أرامكو السعودية (Aramco)", region: "الرياض / الظهران", regions: ["الرياض"], size: "كبيرة", spec: "طاقة، تقنية معلومات، أمن سيبراني، ذكاء اصطناعي", web: "https://www.aramco.com", contact: "careers@aramco.com", linkedin: "https://linkedin.com/company/saudi-aramco", training: "برنامج IDTP وتعاوني — aramco.com/en/careers", grade: "A+", nonSaudi: "نعم — يقبلون طلاب جامعات غير سعوديين" },
  { name: "سابك (SABIC)", region: "الرياض / الجبيل", regions: ["الرياض"], size: "كبيرة", spec: "بتروكيماويات، تحول رقمي، تقنية معلومات", web: "https://www.sabic.com", contact: "sabic.com/en/careers", linkedin: "https://linkedin.com/company/sabic", training: "تعاوني وصيفي — sabic.com/careers", grade: "A+", nonSaudi: "محدود — الأولوية للسعوديين" },
  { name: "الشركة السعودية للكهرباء (SEC)", region: "الرياض (فروع في كل المناطق)", regions: ["الرياض", "حائل", "القصيم"], size: "كبيرة", spec: "طاقة، شبكات ذكية، تقنية معلومات", web: "https://www.se.com.sa", contact: "920000222", linkedin: "https://linkedin.com/company/saudi-electricity-company", training: "تعاوني وتمهير", grade: "A", nonSaudi: "محتمل — الأولوية للسعوديين" },
  { name: "نيوم (NEOM)", region: "الرياض / تبوك", regions: ["الرياض"], size: "كبيرة", spec: "مدينة ذكية، ذكاء اصطناعي، روبوتات، IoT", web: "https://www.neom.com", contact: "neom.com/en-us/careers", linkedin: "https://linkedin.com/company/neom", training: "برامج تدريب — neom.com/careers", grade: "A+", nonSaudi: "نعم — يوظفون كفاءات دولية بشكل نشط" },
  { name: "حلول إس تي سي (Solutions by STC)", region: "الرياض", regions: ["الرياض"], size: "كبيرة", spec: "سحابة، خدمات مُدارة، حلول بنية تحتية", web: "https://solutions.com.sa", contact: "info@stc.com.sa", linkedin: "https://linkedin.com/company/solutionsbystc", training: "COOP & Graduate Programs", grade: "A", nonSaudi: "محدود — أولوية للسعوديين" },
  { name: "الخطوط السعودية (Saudia) — IT", region: "الرياض / جدة", regions: ["الرياض"], size: "كبيرة", spec: "طيران، أنظمة تقنية معلومات", web: "https://www.saudia.com", contact: "920022222", linkedin: "https://linkedin.com/company/saudi-arabian-airlines", training: "تعاوني وتمهير", grade: "A+", nonSaudi: "محتمل — الأولوية للسعوديين" },
  { name: "الخدمات الأرضية السعودية (SGS)", region: "الرياض / جدة", regions: ["الرياض"], size: "كبيرة", spec: "تقنية الطيران، خدمات أرضية", web: "https://www.sgs.com.sa", contact: "sgs.com.sa/careers", linkedin: "https://linkedin.com/company/saudi-ground-services", training: "تعاوني وتمهير", grade: "A", nonSaudi: "محتمل — الأولوية للسعوديين" },
  { name: "معادن (Ma'aden)", region: "الرياض", regions: ["الرياض"], size: "كبيرة", spec: "تعدين، تقنية معلومات، ERP", web: "https://www.maaden.com.sa", contact: "maaden.com.sa/en/careers", linkedin: "https://linkedin.com/company/maaden", training: "تعاوني وتمهير", grade: "B", nonSaudi: "محتمل — الأولوية للسعوديين" },
  { name: "ثقة لخدمات الأعمال (Thiqah)", region: "الرياض", regions: ["الرياض"], size: "كبيرة", spec: "حكومة إلكترونية، تعهيد تقنية", web: "https://www.thiqah.sa", contact: "920009575", linkedin: "https://linkedin.com/company/thiqah", training: "تعاوني", grade: "A", nonSaudi: "محدود — تركز على الكوادر الوطنية" },
  { name: "التعاونية للتأمين (Tawuniya)", region: "الرياض", regions: ["الرياض"], size: "كبيرة", spec: "تأمين، تقنية تأمين رقمية", web: "https://www.tawuniya.com", contact: "920019990", linkedin: "https://linkedin.com/company/tawuniya", training: "تعاوني وتمهير", grade: "A", nonSaudi: "محتمل — الأولوية للسعوديين" },
  { name: "شركة الجريسي (Jeraisy)", region: "الرياض", regions: ["الرياض"], size: "كبيرة", spec: "حلول تقنية، إلكترونيات، نقاط بيع", web: "https://www.jeraisy.com", contact: "920000036", linkedin: "https://linkedin.com/company/jeraisy-group", training: "تعاوني لطلاب الحاسب — متاح للمقيمين", grade: "A", nonSaudi: "محتمل" },
  { name: "نون (Noon)", region: "الرياض (خدمة في كل المناطق)", regions: ["الرياض"], size: "كبيرة", spec: "تجارة إلكترونية، تقنية لوجستيات", web: "https://www.noon.com", contact: "noon.com/contact", linkedin: "https://linkedin.com/company/nooncom", training: "تدريب — noon.com/careers", grade: "A", nonSaudi: "نعم — يقبلون غير السعوديين" },
  { name: "الاتحاد السعودي للأمن السيبراني (SAFCSP)", region: "الرياض", regions: ["الرياض"], size: "حكومية", spec: "أمن سيبراني، برمجة، درونز", web: "https://safcsp.org.sa", contact: "info@safcsp.org.sa", linkedin: "https://linkedin.com/company/safcsp", training: "أكاديمية طويق — معسكرات وتعاوني", grade: "A+", nonSaudi: "نعم — بعض البرامج مفتوحة لغير السعوديين" },
  { name: "سايت (SITE) للتقنية", region: "الرياض", regions: ["الرياض"], size: "كبيرة", spec: "أمن سيبراني، خدمات تقنية", web: "https://www.site.sa", contact: "info@site.sa", linkedin: "https://linkedin.com/company/sitesa", training: "برنامج تطوير الخريجين ADP (للسعوديين فقط)", grade: "A", nonSaudi: "للسعوديين فقط — برنامج ADP" },
  { name: "SRMG — المجموعة السعودية للأبحاث والإعلام", region: "الرياض", regions: ["الرياض"], size: "كبيرة", spec: "إعلام رقمي، تقنية محتوى", web: "https://www.srmg.com/en/contact", contact: "+966 11 212 8000 | info@srmg.com | careers@srmg.com", linkedin: "https://linkedin.com/company/srmg", training: "تعاوني — تقبل المقيمين في الأقسام الرقمية", grade: "A+", nonSaudi: "نعم — تقبل المقيمين" },
  { name: "شركة العرض المتقن (2P)", region: "الرياض", regions: ["الرياض"], size: "كبيرة", spec: "حلول تقنية، أمن سيبراني، تشغيل وصيانة، تطوير برمجيات", web: "https://www.2p.com.sa", contact: "عبر الموقع الرسمي / تواصل معنا", linkedin: "https://www.linkedin.com/company/2pcompanysa/", training: "تدريب وتعاوني عبر وظائف الشركة", grade: "A+", nonSaudi: "محتمل — بحسب الدور واشتراطات الجهة" },
  { name: "تقنية (TAQNIA) — الشركة السعودية للتنمية والاستثمار التقني", region: "الرياض", regions: ["الرياض"], size: "كبيرة", spec: "استثمار تقني، نقل تقنية، أمن ودفاع وتقنيات متقدمة", web: "https://www.taqnia.com", contact: "عبر الموقع الرسمي", linkedin: "", training: "غير معروف", grade: "A+", nonSaudi: "محدود — جهة حكومية/استراتيجية" },
  { name: "مدينة الملك عبدالعزيز للعلوم والتقنية (KACST)", region: "الرياض", regions: ["الرياض"], size: "حكومية", spec: "بحث وتطوير، علوم وتقنية، مراكز ابتكار", web: "https://www.kacst.gov.sa/ar", contact: "عبر بوابة تواصل كاكست", linkedin: "https://www.linkedin.com/company/kacst---employment", training: "برامج بحثية وتدريبية حسب الإعلان", grade: "A", nonSaudi: "محدود — حسب البرنامج" },
  { name: "شركة تحكم (TCC)", region: "الرياض", regions: ["الرياض"], size: "كبيرة", spec: "تقنية تحكم، بنية تحتية رقمية", web: "https://tcc.sa", contact: "tcc.sa", linkedin: "https://linkedin.com/company/tcc-sa", training: "غير معروف", grade: "", nonSaudi: "محتمل — تخصصات دقيقة" },
  { name: "بيان للمعلومات الائتمانية (Bayan)", region: "الرياض", regions: ["الرياض"], size: "كبيرة", spec: "بيانات ائتمانية، ذكاء اصطناعي، تحليلات", web: "https://www.bfrb.com.sa", contact: "920000690", linkedin: "https://linkedin.com/company/bayan-credit-bureau", training: "غير معروف", grade: "A", nonSaudi: "محتمل" },

  // ────────────────────────────────────────────────────────────────
  //  الرياض — متوسطة وناشئة
  // ────────────────────────────────────────────────────────────────
  { name: "تمارا (Tamara)", region: "الرياض", regions: ["الرياض"], size: "متوسطة", spec: "تقنية مالية، اشتر الآن ادفع لاحقاً (BNPL)", web: "https://tamara.co/en-sa/careers/builders", contact: "8001181118", linkedin: "https://linkedin.com/company/tamara-pay", training: "Builders Program (دفعات يناير ويونيو) — مفتوح للجميع", grade: "A+", nonSaudi: "نعم — Builders Program مفتوح بناءً على الكفاءة" },
  { name: "تابي (Tabby)", region: "الرياض", regions: ["الرياض"], size: "متوسطة", spec: "تقنية مالية، مدفوعات رقمية (BNPL)", web: "https://tabby.ai/en-SA/careers", contact: "عبر بوابة التوظيف", linkedin: "https://linkedin.com/company/tabby-ai", training: "Intern Backend Engineer — مفتوح لمطوري React و Go", grade: "A", nonSaudi: "نعم — فريق دولي" },
  { name: "فودكس (Foodics)", region: "الرياض", regions: ["الرياض"], size: "متوسطة", spec: "تقنية مطاعم، نقاط بيع، SaaS", web: "https://www.foodics.com/careers", contact: "foodics.com/contact", linkedin: "https://linkedin.com/company/foodics", training: "Foodics Folks — صيفي وتعاوني للموهوبين المقيمين", grade: "A", nonSaudi: "نعم — ترحب بالموهوبين المقيمين" },
  { name: "لين تكنولوجيز (Lean Technologies)", region: "الرياض", regions: ["الرياض"], size: "متوسطة", spec: "خدمات مصرفية مفتوحة (Open Banking)، APIs", web: "https://leantech.me/careers", contact: "hiring@leantech.me", linkedin: "https://linkedin.com/company/leantech-me", training: "Software Engineering Intern — بيئة دولية مرنة", grade: "A", nonSaudi: "نعم — تركيز عالي على الكفاءة الدولية" },
  { name: "سلة (Salla)", region: "الرياض", regions: ["الرياض"], size: "متوسطة", spec: "منصة تجارة إلكترونية، SaaS", web: "https://salla.com/careers", contact: "920034002", linkedin: "https://linkedin.com/company/sallaapp", training: "تعاوني وصيفي — salla.com/careers", grade: "A", nonSaudi: "محتمل" },
  { name: "زد (Zid)", region: "الرياض", regions: ["الرياض"], size: "متوسطة", spec: "منصة تجارة إلكترونية، SaaS", web: "https://zid.sa/en/contact", contact: "920022223", linkedin: "https://linkedin.com/company/zidsa", training: "تعاوني — «الجنسية لا تهم، الأهم الفضول»", grade: "A", nonSaudi: "نعم — الجنسية لا تهم" },
  { name: "جاهز (Jahez)", region: "الرياض", regions: ["الرياض"], size: "متوسطة", spec: "توصيل طعام، تقنية لوجستيات", web: "https://career.jahez.net", contact: "8001241220", linkedin: "https://linkedin.com/company/jahezksa", training: "برامج تدريب تعاوني", grade: "A", nonSaudi: "محتمل — تواصل مباشر للسياسة" },
  { name: "لوسيديا (Lucidya)", region: "الرياض", regions: ["الرياض"], size: "متوسطة", spec: "ذكاء اصطناعي، تحليلات وسائل التواصل", web: "https://lucidya.com/careers", contact: "920011612", linkedin: "https://linkedin.com/company/lucidya", training: "Technical Internship (AI/Data) — مفتوح للدوليين المتميزين", grade: "A", nonSaudi: "نعم — ترحب بالطلاب الدوليين في AI" },
  { name: "رواء (Rewaa)", region: "الرياض", regions: ["الرياض"], size: "متوسطة", spec: "تقنية تجزئة، نقاط بيع، إدارة مخزون", web: "https://www.rewaatech.com", contact: "rewaatech.com/contact", linkedin: "https://linkedin.com/company/rewaatech", training: "تدريب — rewaatech.com/careers", grade: "", nonSaudi: "نعم — توظيف مفتوح" },
  { name: "مزن (Mozn)", region: "الرياض", regions: ["الرياض"], size: "متوسطة", spec: "ذكاء اصطناعي، تعلم آلي، RegTech", web: "https://www.mozn.sa", contact: "920011613", linkedin: "https://linkedin.com/company/mozn", training: "تعاوني — ترحب بخبراء AI والبيانات", grade: "A", nonSaudi: "محتمل" },
  { name: "يونيفونيك (Unifonic)", region: "الرياض", regions: ["الرياض"], size: "متوسطة", spec: "منصة اتصالات سحابية (CPaaS)، SMS/Voice", web: "https://www.unifonic.com", contact: "unifonic.com/contact", linkedin: "https://linkedin.com/company/unifonic", training: "تدريب تعاوني دولي ومحلي", grade: "", nonSaudi: "نعم — شركة دولية تقبل متدربين متنوعين" },
  { name: "CEQUENS", region: "الرياض", regions: ["الرياض"], size: "متوسطة", spec: "منصة اتصالات سحابية، APIs", web: "https://www.cequens.com", contact: "cequens.com/contact", linkedin: "https://linkedin.com/company/cequens", training: "تدريب", grade: "", nonSaudi: "نعم — توظيف إقليمي" },
  { name: "المعمر لأنظمة المعلومات (MIS)", region: "الرياض", regions: ["الرياض"], size: "متوسطة", spec: "حلول تقنية، تكامل أنظمة", web: "https://www.mis.com.sa", contact: "mis.com.sa/en/contact-us", linkedin: "https://linkedin.com/company/al-moammar-information-systems", training: "تعاوني وتمهير", grade: "", nonSaudi: "غير معروف" },
  { name: "إجادة (Ejada)", region: "الرياض", regions: ["الرياض"], size: "متوسطة", spec: "خدمات تقنية، ERP، استشارات SAP", web: "https://www.ejada.com", contact: "careers@ejada.com", linkedin: "https://linkedin.com/company/ejada", training: "تعاوني وتدريب", grade: "A", nonSaudi: "نعم — قد يقبلون دوليين" },
  { name: "مرسول (Mrsool)", region: "الرياض", regions: ["الرياض"], size: "متوسطة", spec: "توصيل، تقنية لوجستيات", web: "https://www.mrsool.co", contact: "inquiries@mrsool.co", linkedin: "https://linkedin.com/company/mrsool", training: "بيئة ناشئة منفتحة — تواصل مباشر", grade: "A", nonSaudi: "نعم — بيئة منفتحة" },
  { name: "كلاسيرا (Classera)", region: "الرياض", regions: ["الرياض"], size: "متوسطة", spec: "تقنية تعليم، LMS، AI تعليمي", web: "https://www.classera.com", contact: "classera.com/contact-us", linkedin: "https://linkedin.com/company/classera", training: "تعاوني وتدريب", grade: "", nonSaudi: "محتمل" },
  { name: "جيديا (Geidea)", region: "الرياض", regions: ["الرياض"], size: "متوسطة", spec: "تقنية مالية، معالجة مدفوعات", web: "https://www.geidea.net", contact: "geidea.net/contact", linkedin: "https://linkedin.com/company/geidea", training: "تدريب — geidea.net/careers", grade: "", nonSaudi: "نعم — فريق متنوع" },
  { name: "راسن (Rasan)", region: "الرياض", regions: ["الرياض"], size: "متوسطة", spec: "تقنية تأمين، SaaS", web: "https://rfrb.com", contact: "rfrb.com/contact", linkedin: "https://linkedin.com/company/rasan-technology", training: "تعاوني وتدريب", grade: "", nonSaudi: "محتمل" },
  { name: "قوافل (Qawafel)", region: "الرياض", regions: ["الرياض"], size: "متوسطة", spec: "استشارات تقنية، تطوير برمجيات", web: "https://qawafel.com", contact: "qawafel.com/contact", linkedin: "https://linkedin.com/company/qawafel", training: "تعاوني وتمهير", grade: "", nonSaudi: "غير معروف" },
  { name: "قنوات للاتصالات (Qanawat)", region: "الرياض", regions: ["الرياض"], size: "متوسطة", spec: "اتصالات، خدمات القيمة المضافة", web: "https://www.qanawat.com.sa", contact: "qanawat.com.sa/contact", linkedin: "https://linkedin.com/company/qanawat", training: "تعاوني وتمهير", grade: "A+", nonSaudi: "محتمل — يفضلون سعوديين" },
  { name: "ساري (Sary)", region: "الرياض", regions: ["الرياض"], size: "متوسطة", spec: "تجارة B2B، لوجستيات تقنية", web: "https://sary.com", contact: "sary.com/careers", linkedin: "https://linkedin.com/company/saryapp", training: "فرص للمبدعين في اللوجستيات التقنية", grade: "", nonSaudi: "محتمل" },
  { name: "هنقرستيشن (HungerStation)", region: "الرياض", regions: ["الرياض"], size: "كبيرة", spec: "تطبيقات توصيل، لوجستيات تقنية", web: "https://careers.deliveryhero.com/hungerstation-jobs", contact: "عبر بوابة التوظيف", linkedin: "https://linkedin.com/company/hungerstation", training: "تعاوني — تابعة لـ Delivery Hero العالمية", grade: "", nonSaudi: "نعم — كفاءات دولية" },
  { name: "فلوارد (Floward)", region: "الرياض", regions: ["الرياض"], size: "متوسطة", spec: "تجارة إلكترونية (هدايا/ورود)", web: "https://www.floward.com", contact: "floward.com/careers", linkedin: "https://linkedin.com/company/floward", training: "فرص تحوّل لتوظيف كامل للمقيمين", grade: "", nonSaudi: "نعم — فرص للمقيمين" },
  { name: "نينجا (ToYou / Ninja)", region: "الرياض", regions: ["الرياض"], size: "متوسطة", spec: "توصيل سريع، لوجستيات", web: "https://ananinja.com", contact: "عبر التطبيق", linkedin: "https://linkedin.com/company/ananinja", training: "توسع تقني سريع — فرص تدريب", grade: "", nonSaudi: "محتمل" },
  { name: "رناد المجد (Renad Al-Majd / RMG)", region: "الرياض", regions: ["الرياض"], size: "متوسطة", spec: "تحول رقمي، أمن سيبراني، استشارات", web: "https://rmg-sa.com", contact: "wa.me/966542180057", linkedin: "https://linkedin.com/company/rmgsaudi", training: "تواصل مباشر — مشاريع تقنية إقليمية", grade: "", nonSaudi: "نعم — مرنة" },
  { name: "آي سبكترا (iSpectra)", region: "الرياض", regions: ["الرياض"], size: "صغيرة", spec: "UI/UX، دروبال، تطوير ويب", web: "https://ispectra.co", contact: "عبر الموقع", linkedin: "https://linkedin.com/company/ispectra", training: "تدريب — وكالة تقنية تبحث عن المهارات التصميمية", grade: "", nonSaudi: "نعم — متاحة" },
  { name: "OSIT (أوسِت)", region: "الرياض", regions: ["الرياض"], size: "متوسطة", spec: "حلول تقنية، خدمات IT", web: "https://osit.com.sa", contact: "info@osit.com.sa", linkedin: "https://linkedin.com/company/osit", training: "تدريب", grade: "", nonSaudi: "نعم — متاحة" },
  { name: "WNDRGroup — عالم العجب للفنون البصرية", region: "الرياض", regions: ["الرياض"], size: "متوسطة", spec: "فنون بصرية، مؤثرات خاصة، إعلام رقمي", web: "https://www.wndrgroup.com", contact: "info@wndrgroup.com", linkedin: "https://linkedin.com/company/wndrgroup", training: "تعاوني وتدريب", grade: "A+", nonSaudi: "محتمل" },
  { name: "وادي الرياض (RVC)", region: "الرياض", regions: ["الرياض"], size: "متوسطة", spec: "استثمار تقني، ابتكار", web: "https://rvc.com.sa", contact: "عبر الموقع", linkedin: "https://linkedin.com/company/riyadh-valley-company", training: "برامج تدريب عبر الموقع", grade: "", nonSaudi: "نعم — برامج تدريب" },
  { name: "حاسب (Hasib)", region: "الرياض", regions: ["الرياض"], size: "متوسطة", spec: "حلول تقنية، ERP، خدمات حكومية", web: "https://hasib.com.sa", contact: "عبر الموقع", linkedin: "", training: "تعاوني", grade: "", nonSaudi: "نعم — متاحة" },
  { name: "التكامل التقني (Al Takamul Tech / ITC)", region: "الرياض", regions: ["الرياض"], size: "متوسطة", spec: "حلول تقنية، سحابة، تكامل أنظمة", web: "https://itc.com.sa", contact: "info@itc.com.sa", linkedin: "https://linkedin.com/company/altakamultech", training: "تعاوني", grade: "", nonSaudi: "نعم — قد يقبلون" },
  { name: "مساندة (Musanada)", region: "الرياض", regions: ["الرياض"], size: "متوسطة", spec: "خدمات تقنية، دعم فني", web: "https://musanada.com.sa", contact: "info@musanada.sa", linkedin: "https://linkedin.com/company/musanada-saudi", training: "تدريب", grade: "", nonSaudi: "نعم — متاحة" },
  { name: "سحاب كلاود (Elm Cloud)", region: "الرياض", regions: ["الرياض"], size: "متوسطة", spec: "حوسبة سحابية، IaaS", web: "https://sahab.cloud", contact: "sahab.cloud/contact", linkedin: "https://linkedin.com/company/sahabcloud", training: "غير معروف", grade: "", nonSaudi: "غير معروف" },

  // ────────── ناشئة وصغيرة — الرياض ──────────
  { name: "مرني (Morni)", region: "الرياض", regions: ["الرياض"], size: "ناشئة", spec: "مساعدة على الطريق، IoT، لوجستيات", web: "https://morni.com", contact: "morni.com/contact", linkedin: "https://linkedin.com/company/morni", training: "تدريب", grade: "", nonSaudi: "محتمل" },
  { name: "هايبر باي (HyperPay)", region: "الرياض", regions: ["الرياض"], size: "ناشئة", spec: "بوابة دفع، تقنية مالية", web: "https://www.hyperpay.com", contact: "hyperpay.com/contact", linkedin: "https://linkedin.com/company/hyperpay", training: "تعاوني وتدريب", grade: "", nonSaudi: "نعم — توظيف مفتوح" },
  { name: "نعناع (Nana)", region: "الرياض", regions: ["الرياض"], size: "ناشئة", spec: "توصيل بقالة، تجارة إلكترونية", web: "https://www.nfrb.sa", contact: "nfrb.sa/contact", linkedin: "", training: "تدريب", grade: "", nonSaudi: "محتمل" },
  { name: "كالو (Calo)", region: "الرياض", regions: ["الرياض"], size: "ناشئة", spec: "تقنية صحية، اشتراك وجبات", web: "https://www.calo.app", contact: "calo.app/contact", linkedin: "https://linkedin.com/company/caloapp", training: "تدريب", grade: "", nonSaudi: "نعم" },
  { name: "جيكسار (Geexar)", region: "الرياض + مصر", regions: ["الرياض"], size: "صغيرة", spec: "تطوير تطبيقات، ERP، ويب، تسويق", web: "https://geexar.com", contact: "+966 5000 187 59 | info@geexar.com", linkedin: "https://linkedin.com/company/geexar", training: "غير معروف — تواصل مباشر", grade: "", nonSaudi: "نعم — لديهم مكتب في مصر أيضاً" },
  { name: "بروفن سكيورتي (Proven Security)", region: "الرياض", regions: ["الرياض"], size: "صغيرة", spec: "أمن سيبراني، اختبار اختراق", web: "https://proven.sa", contact: "عبر الموقع", linkedin: "", training: "غير معروف", grade: "", nonSaudi: "نعم — متاحة" },
  { name: "آي تي آي إس (iTiS Global)", region: "الرياض", regions: ["الرياض"], size: "صغيرة", spec: "خدمات تقنية، سحابة، بنية تحتية", web: "https://itisglobal.com", contact: "عبر الموقع", linkedin: "https://linkedin.com/company/it-integrated-solutions-itis", training: "غير معروف", grade: "", nonSaudi: "نعم — متاحة" },
  { name: "ارابيان القابضة", region: "الرياض (عن بعد)", regions: ["الرياض", "عن بعد"], size: "صغيرة", spec: "تطوير واجهات (Frontend)", web: "", contact: "عبر لينكد إن", linkedin: "", training: "تدريب عن بعد بمكافأة (1100 دولار) للمقيمين", grade: "", nonSaudi: "نعم — تدريب عن بعد" },

  // ────────── شركات من القائمة الجديدة (صور) — الرياض ──────────
  { name: "هدهد لتقنية المعلومات (HUDHUD AI)", region: "الرياض", regions: ["الرياض"], size: "ناشئة", spec: "ذكاء اصطناعي محادثة، شات بوت، NLP عربي", web: "https://hudhud.ai", contact: "hi@hudhud.ai | join@hudhud.ai", linkedin: "https://linkedin.com/company/hudhud-ai", training: "تواصل: join@hudhud.ai", grade: "", nonSaudi: "محتمل" },
  { name: "جسر (JISR) — إدارة الموارد البشرية", region: "الرياض", regions: ["الرياض"], size: "متوسطة", spec: "HR SaaS، رواتب، توظيف — 4500+ عميل", web: "https://jisr.net", contact: "+966 11 5200 880 | talent@jisr.net", linkedin: "https://linkedin.com/company/jisr-hr", training: "تواصل: talent@jisr.net", grade: "", nonSaudi: "محتمل" },
  { name: "INVENTO", region: "الرياض", regions: ["الرياض"], size: "متوسطة", spec: "منتجات رقمية، منصات اتصال، AI، ERP", web: "https://invento.sa", contact: "+966920012387 | info@invento.sa", linkedin: "https://linkedin.com/company/inventosa", training: "صفحة وظائف: invento.sa/careers", grade: "", nonSaudi: "محتمل" },
  { name: "شركة أبحاث وتطوير الأعمال (T2)", region: "الرياض", regions: ["الرياض"], size: "متوسطة", spec: "منصات رسائل SMS (Msegat)، حلول رقمية — 12K عميل", web: "https://t2.sa", contact: "t2.sa/contact-us", linkedin: "", training: "غير معروف — تواصل مباشرة", grade: "", nonSaudi: "محتمل" },
  { name: "باب العالمية (BAB International)", region: "الرياض", regions: ["الرياض"], size: "متوسطة", spec: "CPaaS، اتصالات، شات بوت AI، SMS — تأسست 1999", web: "https://bab.com.sa", contact: "+966 11 512 1440 | info@bab.com.sa", linkedin: "https://linkedin.com/company/bab-international-corp-for-specialized-services", training: "غير معروف — تواصل مباشرة", grade: "", nonSaudi: "محتمل" },
  { name: "الوطنية لحماية الاتصالات والمعلومات (NTIS)", region: "الرياض", regions: ["الرياض"], size: "متوسطة", spec: "أمن معلومات، حماية اتصالات، أمن سيبراني", web: "https://www.ntis.com.sa", contact: "عبر الموقع", linkedin: "", training: "غير معروف", grade: "", nonSaudi: "غير معروف" },
  { name: "الأساليب الذكية (Smart Methods)", region: "الرياض", regions: ["الرياض"], size: "صغيرة", spec: "تدريب تقني، ذكاء اصطناعي، تأهيل مهني", web: "https://smartmethods.sa", contact: "عبر الموقع", linkedin: "", training: "مركز تدريب تقني — برامج تأهيل", grade: "", nonSaudi: "محتمل" },
  { name: "جوراء (JAWRAA)", region: "الرياض", regions: ["الرياض"], size: "متوسطة", spec: "تحول رقمي، أنظمة سحابية، حلول تقنية", web: "https://jawraa.com", contact: "jawraa.com/contact-us", linkedin: "https://linkedin.com/company/jawraa", training: "غير معروف", grade: "", nonSaudi: "غير معروف" },
  { name: "Global Knowledge السعودية", region: "الرياض", regions: ["الرياض"], size: "كبيرة", spec: "تدريب تقني معتمد: AWS، سيسكو، مايكروسوفت، AI", web: "https://www.globalknowledge.com/en-sa", contact: "globalknowledge.com/en-sa/contact", linkedin: "https://linkedin.com/company/global-knowledge", training: "مركز تدريب معتمد — دورات وشهادات احترافية", grade: "", nonSaudi: "نعم — تدريب مفتوح للجميع" },
  { name: "الإلكترونيات المتقدمة (AEC)", region: "الرياض", regions: ["الرياض"], size: "كبيرة", spec: "إلكترونيات، تصنيع تقني، أنظمة دفاعية", web: "https://www.aecl.com", contact: "عبر الموقع", linkedin: "", training: "تعاوني", grade: "A+", nonSaudi: "محدود" },
  { name: "بيكسل لتقنية المعلومات (Pixel)", region: "الرياض", regions: ["الرياض"], size: "صغيرة", spec: "استشارات بنية تحتية، ICT، حلول ذكية", web: "https://pixel-sa.com", contact: "info@pixel-sa.com", linkedin: "", training: "غير معروف", grade: "", nonSaudi: "محتمل" },
  { name: "جودين (Jodayn)", region: "الرياض", regions: ["الرياض"], size: "صغيرة", spec: "هندسة أنظمة، استشارات تقنية", web: "https://jodayn.com", contact: "عبر الموقع", linkedin: "", training: "غير معروف — تواصل مباشر", grade: "", nonSaudi: "غير معروف" },
  { name: "Aggregate Shield", region: "الرياض", regions: ["الرياض"], size: "صغيرة", spec: "أمن سيبراني — مرخصة من هيئة الأمن السيبراني", web: "", contact: "عبر هيئة الأمن السيبراني", linkedin: "", training: "غير معروف", grade: "", nonSaudi: "غير معروف" },
  { name: "4D Medical", region: "الرياض", regions: ["الرياض"], size: "صغيرة", spec: "مراكز اتصال، تقنية صحية", web: "https://4d.com.sa", contact: "عبر الموقع", linkedin: "", training: "غير معروف — تواصل مباشر", grade: "", nonSaudi: "غير معروف" },
  { name: "نادي الرياض للتقنية (Riyadh Polytechnic)", region: "الرياض", regions: ["الرياض"], size: "حكومية", spec: "تدريب مهني متخصص، تقنية معلومات", web: "https://rpi.edu.sa", contact: "rpi.edu.sa/training/cooperative-training", linkedin: "https://linkedin.com/school/riyadh-polytechnic-institute", training: "برنامج «شارك» للتدريب التعاوني", grade: "A", nonSaudi: "محتمل" },

  // ────────── عن بعد ──────────
  { name: "GAO Tek — تدريب عن بعد", region: "عن بعد (Remote)", regions: ["عن بعد"], size: "كبيرة", spec: "برمجة، IT، وردبريس — تدريب عن بعد", web: "https://sa.gaotek.com/careers/internships/", contact: "عبر الموقع", linkedin: "https://linkedin.com/company/gao-tek-inc", training: "تدريب عن بعد متاح لجميع المقيمين", grade: "", nonSaudi: "نعم — متاح لجميع المقيمين" },

  // ────────────────────────────────────────────────────────────────
  //  حائل — شركات وجهات محلية حقيقية
  // ────────────────────────────────────────────────────────────────
  { name: "جامعة حائل — عمادة تقنية المعلومات", region: "حائل", regions: ["حائل"], size: "حكومية", spec: "تقنية معلومات أكاديمية، بحث، شبكات", web: "https://www.uoh.edu.sa", contact: "0165341011 | helpdesk@uoh.edu.sa", linkedin: "https://linkedin.com/company/university-of-hail", training: "تعاوني لطلاب جامعة حائل — شراكات مع Dell/Cisco/Microsoft", grade: "A+", nonSaudi: "طلاب الجامعة" },
  { name: "إدارة الأمن السيبراني — جامعة حائل", region: "حائل", regions: ["حائل"], size: "حكومية", spec: "أمن سيبراني، حماية أصول رقمية", web: "https://www.uoh.edu.sa", contact: "0165341011 | cyber@uoh.edu.sa", linkedin: "", training: "تعاوني وتدريب للأمن السيبراني", grade: "A", nonSaudi: "طلاب الجامعة" },
  { name: "فضاء أجا لتقنية المعلومات (Aja Space)", region: "حائل", regions: ["حائل"], size: "متوسطة", spec: "تطوير برمجيات، أمن سيبراني، حلول تقنية", web: "", contact: "حائل - حي الشفاء", linkedin: "https://linkedin.com/company/ajaspace", training: "تعاوني وتدريب", grade: "A+", nonSaudi: "نعم" },
  { name: "غرفة حائل التجارية", region: "حائل", regions: ["حائل"], size: "حكومية", spec: "خدمات أعمال، تحول رقمي", web: "https://hailcci.org.sa", contact: "920002820", linkedin: "", training: "تسهيل شراكات تدريبية", grade: "B", nonSaudi: "محتمل" },
  { name: "شركة أسمنت حائل (Hail Cement Co.)", region: "حائل", regions: ["حائل"], size: "كبيرة", spec: "تصنيع، ERP، تقنية معلومات", web: "https://www.hailcement.com", contact: "0165344444", linkedin: "", training: "تعاوني في قسم التقنية", grade: "B", nonSaudi: "محتمل" },
  { name: "حائل الزراعية (HADCO)", region: "حائل", regions: ["حائل"], size: "كبيرة", spec: "زراعة، ERP، IoT، أنظمة ري ذكية", web: "https://www.hadco.com.sa", contact: "hadco.com.sa/contact", linkedin: "https://linkedin.com/company/hadco", training: "تعاوني وتمهير في قسم التقنية", grade: "", nonSaudi: "محتمل" },
  { name: "خبراء التقنية (T-Experts)", region: "حائل", regions: ["حائل"], size: "صغيرة", spec: "أنظمة، استشارات، تدريب تقني", web: "https://www.t-experts.com/ar/", contact: "training@t-experts.com", linkedin: "https://linkedin.com/company/t-experts", training: "مركز تدريب واستشارات — تواصل مباشر", grade: "", nonSaudi: "نعم — متاحة" },
  { name: "كيان رحلة لتقنية المعلومات", region: "حائل", regions: ["حائل"], size: "صغيرة", spec: "خدمات تقنية المعلومات", web: "https://d2020.net/public/details/1011162", contact: "0126059755", linkedin: "", training: "تواصل مباشر", grade: "", nonSaudi: "غير معروف" },
  { name: "مؤسسة غصن يثرب لتقنية المعلومات", region: "حائل", regions: ["حائل"], size: "صغيرة", spec: "خدمات تقنية، صيانة، شبكات", web: "", contact: "", linkedin: "", training: "تعاوني", grade: "", nonSaudi: "محتمل" },
  { name: "درع الأمان الرقمي للاتصالات وتقنية المعلومات", region: "حائل", regions: ["حائل"], size: "صغيرة", spec: "أمن سيبراني، حماية رقمية", web: "", contact: "info@digitalshield.sa", linkedin: "", training: "تدريب", grade: "A+", nonSaudi: "محتمل" },
  { name: "معهد العلياء العالي للتدريب — حائل", region: "حائل", regions: ["حائل"], size: "متوسطة", spec: "تدريب تقني، شبكات، حاسب", web: "https://alalyaa.sa", contact: "0165330055", linkedin: "", training: "دبلومات ودورات تقنية", grade: "A", nonSaudi: "نعم" },
  { name: "معهد كفاءات المستقبل العالي — حائل", region: "حائل", regions: ["حائل"], size: "متوسطة", spec: "علوم حاسب، تقنية معلومات", web: "https://kafaat-store.com", contact: "0550081122", linkedin: "", training: "دبلومات معتمدة", grade: "A", nonSaudi: "نعم" },
  { name: "أكاديمية أثر (Athr Academy)", region: "حائل · الرياض", regions: ["حائل", "الرياض"], size: "صغيرة", spec: "بيانات، ذكاء اصطناعي، معسكرات", web: "https://atharhubs.com", contact: "واتساب: 0532616771", linkedin: "", training: "معسكرات ودورات — تدريب مكثف", grade: "", nonSaudi: "نعم" },
  { name: "دؤوب (Daoob) — معهد تدريب", region: "حائل · القصيم", regions: ["حائل", "القصيم"], size: "صغيرة", spec: "تطوير ويب، تطبيقات، تسويق رقمي", web: "https://daoob.sa", contact: "0541276633 | Daoob.tr@gmail.com", linkedin: "https://linkedin.com/company/daoob", training: "تدريب تقني", grade: "B", nonSaudi: "نعم" },

  // ────────────────────────────────────────────────────────────────
  //  القصيم — شركات وجهات محلية حقيقية
  // ────────────────────────────────────────────────────────────────
  { name: "جامعة القصيم — عمادة تقنية المعلومات", region: "القصيم", regions: ["القصيم"], size: "حكومية", spec: "تقنية معلومات أكاديمية، بحث، ERP", web: "https://www.qu.edu.sa", contact: "0163800050", linkedin: "https://linkedin.com/company/qassim-university", training: "تعاوني إلزامي لطلاب الحاسب", grade: "A+", nonSaudi: "طلاب الجامعة" },
  { name: "كليات الراجحي — البكيرية", region: "القصيم", regions: ["القصيم"], size: "حكومية", spec: "تقنية تعليمية، أنظمة صحية", web: "https://rfaculty.com.sa", contact: "0163359999", linkedin: "", training: "تعاوني لطلاب الكلية", grade: "A", nonSaudi: "طلاب الكلية" },
  { name: "أوبال لتقنية المعلومات (Opal Technology)", region: "القصيم — بريدة", regions: ["القصيم"], size: "صغيرة", spec: "بنية تحتية، أنظمة أمنية، شبكات — تأسست 2012", web: "https://opal-t.com.sa", contact: "+966163238885 | info@opal-t.com.sa | +966507366227", linkedin: "", training: "تعاوني — تقبل تدريب المقيمين", grade: "A", nonSaudi: "نعم — تواصل مباشر" },
  { name: "P4IT بكسل — تصميم وبرمجة", region: "القصيم", regions: ["القصيم"], size: "صغيرة", spec: "تصميم مواقع، تطبيقات", web: "https://p4it.sa", contact: "info@p4it.sa", linkedin: "https://linkedin.com/company/p4it", training: "تواصل مباشر — شركة محلية منفتحة", grade: "", nonSaudi: "نعم — ترحب بالمبدعين" },
  { name: "أنظمة عون — نظم (Nozzm)", region: "القصيم", regions: ["القصيم"], size: "صغيرة", spec: "حلول فواتير، أنظمة برمجية", web: "https://www.nozzm.com", contact: "0536245555", linkedin: "", training: "تواصل مباشر", grade: "", nonSaudi: "محتمل" },
  { name: "كود لوب (Codlop)", region: "القصيم", regions: ["القصيم"], size: "صغيرة", spec: "برمجة مواقع، حلول تقنية", web: "https://codlop.sa", contact: "sales@codlop.sa", linkedin: "", training: "تواصل — ترحب بالكفاءات", grade: "", nonSaudi: "نعم" },
  { name: "الدقة الذكية لتقنية المعلومات", region: "القصيم", regions: ["القصيم"], size: "صغيرة", spec: "برمجة مواقع، تطبيقات، جرافيكس", web: "https://aldqh.com", contact: "0163238885", linkedin: "", training: "تعاوني ودورات تقنية", grade: "A", nonSaudi: "نعم" },
  { name: "مؤسسة رؤى برمجية (Visooft)", region: "القصيم", regions: ["القصيم"], size: "صغيرة", spec: "حلول برمجية، تطبيقات، متاجر", web: "https://visooft.com", contact: "info@visooft.com", linkedin: "", training: "تعاوني", grade: "A", nonSaudi: "نعم" },
  { name: "بانوراما القصيم للبرمجة والتصميم", region: "القصيم", regions: ["القصيم"], size: "متوسطة", spec: "تطوير ويب، تطبيقات، حلول رقمية", web: "https://panorama-q.com", contact: "0163238885", linkedin: "", training: "تعاوني وتدريب", grade: "A", nonSaudi: "نعم" },
  { name: "إنتر كوميونيكيشنز (Inter Communications)", region: "القصيم — بريدة", regions: ["القصيم"], size: "متوسطة", spec: "اتصالات، شبكات، بنية تحتية", web: "", contact: "بريدة - السادة - مبنى الراجحي | 0163231122", linkedin: "", training: "تعاوني", grade: "A", nonSaudi: "نعم" },
  { name: "أتمال (Atmaal)", region: "الرياض · القصيم", regions: ["الرياض", "القصيم"], size: "صغيرة", spec: "تطوير ويب، حلول تقنية — فروع متعددة", web: "https://careers.atmaal.sa", contact: "info@atmaal.sa", linkedin: "https://linkedin.com/company/atmaal", training: "تعاوني — فرع بريدة + الرياض", grade: "B", nonSaudi: "نعم — فروع متعددة" },
  { name: "غرفة القصيم التجارية", region: "القصيم", regions: ["القصيم"], size: "حكومية", spec: "خدمات أعمال، رقمنة", web: "https://qcci.org.sa", contact: "920004470", linkedin: "", training: "تسهيل شراكات تدريبية", grade: "A", nonSaudi: "محتمل" },
  { name: "الرواد الوطنية (Al Rawad National)", region: "القصيم", regions: ["القصيم"], size: "صغيرة", spec: "خدمات تقنية، شبكات — تعاون مع تقني القصيم", web: "https://rowadalaamal.com", contact: "عبر الموقع", linkedin: "", training: "تعاوني", grade: "", nonSaudi: "نعم" },
  { name: "MTE IT", region: "القصيم — بريدة", regions: ["القصيم"], size: "صغيرة", spec: "تطوير تطبيقات أندرويد و iOS", web: "", contact: "بريدة - طريق علي بن أبي طالب 3365", linkedin: "", training: "تعاوني", grade: "B", nonSaudi: "نعم" },
  { name: "نورتك (NourTech)", region: "القصيم — بريدة", regions: ["القصيم"], size: "صغيرة", spec: "حلول تقنية، تطوير ويب", web: "", contact: "بريدة - طريق الملك عبدالعزيز", linkedin: "", training: "تعاوني", grade: "B", nonSaudi: "نعم" },
  { name: "فيوتشر سيستمز (Future Systems IT)", region: "القصيم — بريدة", regions: ["القصيم"], size: "صغيرة", spec: "حلول تقنية، تكامل أنظمة", web: "", contact: "بريدة - طريق الملك عبدالعزيز", linkedin: "", training: "تعاوني", grade: "B", nonSaudi: "محتمل" },
  { name: "ساينس سوفت (Science Soft)", region: "القصيم — بريدة", regions: ["القصيم"], size: "صغيرة", spec: "تطوير برمجيات", web: "", contact: "بريدة", linkedin: "", training: "تعاوني", grade: "B", nonSaudi: "نعم" },
  { name: "إنفوسيستا (InfoCesta)", region: "القصيم — بريدة", regions: ["القصيم"], size: "صغيرة", spec: "استضافة، سحابة، بنية تحتية", web: "", contact: "بريدة", linkedin: "", training: "تعاوني", grade: "B", nonSaudi: "محتمل" },
  { name: "إفهاص للتدريب (Efhas)", region: "القصيم", regions: ["القصيم"], size: "صغيرة", spec: "تدريب تقني، تطوير مهني", web: "https://efhas.sa", contact: "0554025589 | info@efhas.sa", linkedin: "", training: "مركز تدريب — يقبل متدربين", grade: "", nonSaudi: "نعم" },
  { name: "قصيم تك (Qassim Tech Association)", region: "القصيم", regions: ["القصيم"], size: "صغيرة", spec: "جمعية تقنية غير ربحية، تطوير برمجيات", web: "https://qassim.tech", contact: "info@qassim.tech | واتساب: +966536070230", linkedin: "", training: "التقديم على التدريب عبر qassim.tech/training2025", grade: "A", nonSaudi: "نعم — جمعية غير ربحية" },
  { name: "معهد العلوم الإدارية العالي — القصيم", region: "القصيم", regions: ["القصيم"], size: "متوسطة", spec: "تقنية معلومات، إدارة", web: "https://hiastsa.com", contact: "0163251111", linkedin: "", training: "دبلومات تقنية معتمدة", grade: "A", nonSaudi: "نعم" },
  { name: "أمانة القصيم — تقنية المعلومات", region: "القصيم", regions: ["القصيم"], size: "حكومية", spec: "خدمات إلكترونية، نظم معلومات جغرافية", web: "https://qassim.gov.sa", contact: "0163222222", linkedin: "", training: "تعاوني", grade: "A", nonSaudi: "محدود" },

  // ────────────────────────────────────────────────────────────────
  //  شركات خارجية تخدم السوق السعودي (عن بعد)
  // ────────────────────────────────────────────────────────────────
  { name: "خِليج للبرمجيات (Khelj)", region: "مصر (تخدم السعودية عن بعد)", regions: ["عن بعد"], size: "صغيرة", spec: "تطوير ويب، Odoo، تطبيقات جوال — مقرها مصر (المنصورة)", web: "https://khelj.com", contact: "+201029222350 | عبر الموقع", linkedin: "https://linkedin.com/in/abdulrahman-abdullah-8958331a6", training: "تواصل مباشر — فريق من مصر والسعودية", grade: "", nonSaudi: "نعم — شركة مصرية" },
  { name: "ريديك (Redicc IT)", region: "مصر (تخدم القصيم عن بعد)", regions: ["عن بعد"], size: "صغيرة", spec: "تسويق وسائل التواصل، تصميم ويب — مقرها مصر", web: "https://redicc.net", contact: "واتساب: +201097884414", linkedin: "https://linkedin.com/company/redicc-it", training: "تواصل مباشر — تدعم المبدعين", grade: "", nonSaudi: "نعم — شركة مصرية" },
  { name: "سيمبا ويب (Sympaweb)", region: "الأردن (تخدم السعودية عن بعد)", regions: ["عن بعد"], size: "صغيرة", spec: "تصميم مواقع، تسويق — مقرها عمّان، الأردن", web: "https://sympaweb.com", contact: "+962-779-207012 | info@sympaweb.com", linkedin: "", training: "تواصل مباشر", grade: "", nonSaudi: "نعم — شركة أردنية" },
];
